### ISSUE TITLE
Training new models

### ISSUE THREAD

**Issue by siwel** [mosessoh/iconcolor#1]
Hey, Awesome Project 

It would be great if there were a step by step guide on how to go about training a new model / adding a new style.

Thanks,
Lewis

**Comment by mosessoh** [comment]
Hey there @siwel. Could you take a look at my [poster](https://github.com/mosessoh/iconcolor#poster) and [medium post](https://medium.com/@moses.soh/towards-automatic-icon-design-using-machine-learning-423cbe6710fe) and send me more specific questions?

I'm happy to help but I don't have to time to answer too broad a question due to my work commitments. Glad you've taken an interest - this is an interesting topic!
